version: "3.9"
services:
  haoyang_ctf:
    container_name: haoyangma_ctf
    build:
      context: .
      dockerfile: Dockerfile
      target: haoyangma_ctf
    networks:
      nw0:
    ports:
    - 9500:5000
networks:
  nw0:
    external: true

