version: "3.9"
services:
  ctf_mysql:
    container_name: haoyangma_ctf_mysql
    build:
      context: .
      dockerfile: Dockerfile
      target: mysql
    networks:
      mynet:
        ipv4_address: 172.18.0.3
    ports:
    - 4306:33063

  ctf_python:
    container_name: haoyangma_ctf_python
    build:
      context: .
      dockerfile: Dockerfile
      target: python
    networks:
      mynet:
        ipv4_address: 172.18.0.2
    ports:
    - 9500:5000

  
networks:
  mynet:
    ipam:
      config:
      - subnet: 172.18.0.0/24

